[package]
name = "saboten"
version = "0.0.1"
authors = ["Christian Fischer <christian@chfi.se>"]
description = "Provides biedged graphs, cactus graphs and trees, and an algorithm for finding ultrabubbles in variation graphs."
edition = "2018"
license = "MIT"
repository = "https://github.com/chfi/saboten"
readme = "readme.md"
keywords = ["bioinformatics", "graph"]
categories = ["science"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gfa = "0.8"
three-edge-connected = "0.1"
petgraph = "0.5.0"
bstr = "0.2"
structopt = "0.3"
fnv = "1.0"
rayon = "1.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
log = "0.4"
env_logger = "0.7"
pretty_env_logger = "0.4"
