[package]
name = "rs-cactusgraph"
version = "0.1.0"
authors = ["Christian Fischer <christian@chfi.se>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
petgraph = "0.5.0"
gfa = "0.8"
three-edge-connected = "0.1"
bstr = "0.2"
structopt = "0.3"
fnv = "1.0"
rayon = "1.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
