[package]
name = "rs-cactusgraph"
version = "0.1.0"
authors = ["Francesco Porto <francesco.porto97@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
petgraph = "0.5.0"
gfa = "0.8"
three-edge-connected = { git = "https://github.com/chfi/rs-3-edge", rev = "e820360718047668dc66371274bdd756dcfe41bf" }
bstr = "0.2"
structopt = "0.3"
fnv = "1.0"
